default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV.fetch('DB_HOST') %>

development:
  <<: *default
  database: gem_counter_development

test:
  <<: *default
  database: gem_counter_test

production:
  <<: *default
  database: gem_counter_production
